services:
  - type: web
    name: student-market
    env: node
    startCommand: node server-pg.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_MODE
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: student-db
          property: connectionString

databases:
  - name: student-db
    databaseName: studentmarket
    plan: free
